openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/todos:
    get:
      summary: すべてのTodo項目を取得します。
      operationId: Todo
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: 新しいTodo項目を作成します。
      operationId: Todo
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: hghtvsqsjtithpakl
                description:
                  type: string
                  description: ''
                  example: 'Vel et velit placeat sed cum.'
                is_completed:
                  type: boolean
                  description: ''
                  example: true
                due_date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2024-06-03T08:50:44'
              required:
                - title
      security: []
  '/api/todos/{id}':
    get:
      summary: 指定されたTodo項目の詳細を取得します。
      operationId: Todo
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: 指定されたTodo項目を更新します。
      operationId: Todo
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: yiupeflnawpzlkcc
                description:
                  type: string
                  description: ''
                  example: 'Optio occaecati voluptatem quo neque.'
                is_completed:
                  type: boolean
                  description: ''
                  example: false
                due_date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2024-06-03T08:50:44'
              required:
                - title
      security: []
    delete:
      summary: 指定されたTodo項目を削除します。
      operationId: Todo
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the todo.'
        example: accusamus
        required: true
        schema:
          type: string
  '/api/user/{user}/update':
    put:
      summary: ユーザー情報の更新を行います。
      operationId: ''
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: fdjwzcbjceoguonjbd
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: obeatty@example.org
                password:
                  type: string
                  description: 'Must be at least 6 characters.'
                  example: 'tOO9,h'
      security: []
    parameters:
      -
        in: path
        name: user
        description: 'The user.'
        example: aperiam
        required: true
        schema:
          type: string
  /api/profile:
    get:
      summary: 現在認証されているユーザーのプロファイルを取得します。
      operationId: ''
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/register:
    post:
      summary: ユーザー登録を行います。
      operationId: ''
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: oyafuffkfzlyfjwslbs
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: dklein@example.net
                password:
                  type: string
                  description: 'Must be at least 6 characters.'
                  example: '\Rq]d5K&'
              required:
                - name
                - email
                - password
      security: []
  /api/login:
    post:
      summary: ユーザー認証（ログイン）を行います。
      operationId: ''
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: ratke.emilia@example.com
                password:
                  type: string
                  description: ''
                  example: "N>zr0'bkG{,b_Yu"
              required:
                - email
                - password
      security: []
tags:
  -
    name: Endpoints
    description: ''
